### 진에어 국제선 사이트 크롤링
- 국제선 사이트는 .net aspx 로 개발되어 단계가 복잡함
    * 국제선 예매사이트 1차 접속 : 'https://www.jinair.com/bookflight/flightSearch.aspx'
    * 국제선 예매사이트 viewstate 값얻기 위한 2차 접속, 출발지 선택시 웹페이지에서 호출됨
    * 국제선 예매사이트 최종 검색 1단계 진행 : 다음 버튼 클릭 처리
    * 버튼 클릭시 새창으로 연결 : 'https://www.jinair.com/BookFlight/BookingProcess.aspx'
    * 새창이 열린후 다른 URL로 변경 : 'https://www.jinair.com/BookFlight/FlightSearchBridge.aspx'
        - 이때 최종 검색을 위한 파라미터를 생성 및 검색 페이지 URL 얻어옮
    * 최종 검색 정보 읽어오는 페이지를 이용 정보 검색
        - 자바스크립터로 처리 되고 있음, 필요한 JSON 부분만 발췌하여 처리

In [1]:
import requests
from bs4 import BeautifulSoup
from datetime import datetime
from datetime import timedelta
import json
import pandas as pd
from common.parsing_util import r_flatten, mining_value_by_last_field_name, stat_fare
from common.util import find_between

ImportError: No module named 'common'

In [ ]:
## 출도착지 코드 형식 준수, 날짜 형식 준수
def crawling_LJ_data(dpt,arr,dpt_date):
    print('Crawling jinair homepage schedule site')
    print('Param : ',dpt,arr,dpt_date)
    today = datetime.today().strftime('%Y-%m-%d')
    ## 국제선 예매사이트 1차 접속
    url = 'https://www.jinair.com/bookflight/flightSearch.aspx'
    head = {
        'Referer':'https://www.jinair.com/bookflight/flightSearch.aspx',
        'User-Agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
    }
    sess = requests.Session()
    req = sess.get(url,headers=head)
    soup = BeautifulSoup(req.text,'lxml')

    ## 국제선 예매사이트 viewstate 값얻기 위한 2차 접속, 출발지 선택시 웹페이지에서 호출됨
    param = {
        'ctl00$ScriptManager1':'ctl00$ContentPlaceHolder$UpdatePanel7|ctl00$ContentPlaceHolder$ddlGDeparture',
        '__EVENTTARGET':'ctl00$ContentPlaceHolder$ddlGDeparture',
        '__EVENTARGUMENT':'',
        '__LASTFOCUS':'',
        '__VIEWSTATE':soup.select('#__VIEWSTATE')[0]['value'],
        '__VIEWSTATEGENERATOR':'52375EB0',
        'ctl00$ContentPlaceHolder$rdoItnerary':'2',
        'ctl00$ContentPlaceHolder$ddlGDeparture':dpt,
        'ctl00$ContentPlaceHolder$ddlCDeparture':'',
        'ctl00$ContentPlaceHolder$txtFrom':today,  ## today로 처리
        'ctl00$ContentPlaceHolder$txtTo':today,
        'ctl00$ContentPlaceHolder$ddlAdult':'1',
        'ctl00$ContentPlaceHolder$ddlChild':'0',
        'ctl00$ContentPlaceHolder$ddlInfant':'0',
        'ctl00$ContentPlaceHolder$SearchType':'rdoSchedule',
        'BDC_VCID_c_bookflight_flightsearch_ctl00_contentplaceholder_debotcaptcha':'05038f944aa44d53996721b3b81476fe',
        'BDC_BackWorkaround_c_bookflight_flightsearch_ctl00_contentplaceholder_debotcaptcha':'1',
        'ctl00$ContentPlaceHolder$txtCaptchaCode':'',
        'ctl00$ContentPlaceHolder$hdnDriven':'F',
        'ctl00$ContentPlaceHolder$hdnIsCharterIssue':'',
        'ctl00$ContentPlaceHolder$hdnDepRgnName':'/한국/한국//한국//동남아/동남아/동남아/동남아/동남아/동남아/동남아/동남아//동남아//중국/중국/중국/중국//중국//일본/일본/일본/일본/일본//일본//대양주//대양주//미주',
        'ctl00$ContentPlaceHolder$hdnArrRgnName':'/중국/중국',
        'ctl00$ContentPlaceHolder$hdnRequestVerifyToken':'',
        'ctl00$ContentPlaceHolder$hdCorpCode':'',
        'ctl00$ContentPlaceHolder$hdPromoCode':'',
        'ctl00$ContentPlaceHolder$hdTcpCnt':'',
    }
    req = sess.post(url,param,headers=head)
    soup = BeautifulSoup(req.text,'lxml')

    ## 국제선 예매사이트 최종 검색 1단계 진행
    param = {
        '__EVENTTARGET':'ctl00$ContentPlaceHolder$ibtnNextStep',
        '__EVENTARGUMENT':'',
        '__LASTFOCUS':'',
        '__VIEWSTATE':soup.select('#__VIEWSTATE')[0]['value'],
        '__VIEWSTATEGENERATOR':'52375EB0',
        'ctl00$ContentPlaceHolder$rdoItnerary':'1',
        'ctl00$ContentPlaceHolder$ddlGDeparture':dpt,
        'ctl00$ContentPlaceHolder$ddlCDeparture':arr,
        'ctl00$ContentPlaceHolder$txtFrom':dpt_date,  ## 검색 날짜
        'ctl00$ContentPlaceHolder$txtTo':'',
        'ctl00$ContentPlaceHolder$ddlAdult':'1',
        'ctl00$ContentPlaceHolder$ddlChild':'0',
        'ctl00$ContentPlaceHolder$ddlInfant':'0',
        'ctl00$ContentPlaceHolder$SearchType':'rdoSchedule',
        'BDC_VCID_c_bookflight_flightsearch_ctl00_contentplaceholder_debotcaptcha':'05038f944aa44d53996721b3b81476fe',
        'BDC_BackWorkaround_c_bookflight_flightsearch_ctl00_contentplaceholder_debotcaptcha':'1',
        'ctl00$ContentPlaceHolder$txtCaptchaCode':'',
        'ctl00$ContentPlaceHolder$hdnDriven':'F',
        'ctl00$ContentPlaceHolder$hdnIsCharterIssue':'',
        'ctl00$ContentPlaceHolder$hdnDepRgnName':'/한국/한국//한국//동남아/동남아/동남아/동남아/동남아/동남아/동남아/동남아//동남아//중국/중국/중국/중국//중국//일본/일본/일본/일본/일본//일본//대양주//대양주//미주',
        'ctl00$ContentPlaceHolder$hdnArrRgnName':'/동남아/동남아/동남아/동남아/동남아/동남아/동남아/동남아//동남아//중국//중국//일본/일본/일본/일본/일본//일본//대양주//대양주//미주',
        'ctl00$ContentPlaceHolder$hdnRequestVerifyToken':'',
        'ctl00$ContentPlaceHolder$hdCorpCode':'',
        'ctl00$ContentPlaceHolder$hdPromoCode':'',
        'ctl00$ContentPlaceHolder$hdTcpCnt':'',
    }
    req = sess.post(url,param,headers=head)
    #soup = BeautifulSoup(req.text,'lxml')

    ## 신규 창 생성
    url = 'https://www.jinair.com/BookFlight/BookingProcess.aspx'
    req = sess.get(url,headers=head)

    ## 다른 URL 로 이동
    url = 'https://www.jinair.com/BookFlight/FlightSearchBridge.aspx'
    head = {
        'Referer':'https://www.jinair.com/BookFlight/BookingProcess.aspx',
        'User-Agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
    }
    req = sess.get(url,headers=head)
    soup = BeautifulSoup(req.text,'lxml')

    ## 파라미터 생성
    param = {}
    inputs = soup.select('input')
    for field in inputs:
        param[field['id']] = field['value']
    target_url = param['hdnFormAction']
    target_method = param['hdnFormMethod']

    head = {
        'Referer':'https://www.jinair.com/BookFlight/FlightSearchBridge.aspx',
        'User-Agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
    }

    req = sess.post(target_url,param,headers=head)

    ## 읽어온 데이터중 필요한 JSON 데이터 부분 추출
    raw_data = req.text.replace('\n','').replace(' ','').replace('\\"','')
    start_txt = 'plnextv2.utils.pageProvider.PlnextPageProvider.init({config:'
    end_txt = ',pageEngine'
    print('End crawling')
    return find_between(raw_data,start_txt,end_txt)

In [ ]:
def raw_to_df(raw_data):
    json_data = json.loads(raw_data)

    ## 플라이트 정보 생성
    try:
        raw_flight_info = json_data['pageDefinitionConfig']['pageData']['business']['Availability']['proposedBounds'][0]
        key_fields = ['proposedBoundId', 'beginDate','endDate','flightNumber']
    except Exception as e:
        ## 정보가 없을 경우
        print('****** No Record ******')
        return None
    flight_infos = mining_value_by_last_field_name(raw_flight_info, key_fields)

    ## 가격 정보 생성
    raw_fare_info = json_data['pageDefinitionConfig']['pageData']['business']['Availability']['recommendations']
    fare_infos = {
        'flightId':[],
        'numberOfSeatsLeft':[],
        'ffCode':[],
        'amountWithoutTax':[],
        'tax':[]
    }
    for fare_info in raw_fare_info:
        for flight_group in fare_info['bounds'][0]['flightGroupList']:
            ## 정보 추출
            fare_infos['flightId'].append(flight_group['flightId'])
            fare_infos['numberOfSeatsLeft'].append(flight_group['numberOfSeatsLeft'])
            fare_infos['ffCode'].append(fare_info['fareFamily']['ffCode'])
            fare_infos['amountWithoutTax'].append(fare_info['PNRprices'][0]['recoAmounts'][0]['recoAmount']['amountWithoutTax'])
            fare_infos['tax'].append(fare_info['PNRprices'][0]['recoAmounts'][0]['recoAmount']['tax'])

    ## proposedBoundId 와 flightId 기준으로 join
    df = pd.merge(pd.DataFrame(flight_infos),pd.DataFrame(fare_infos),left_on='proposedBoundId',right_on='flightId')
    ## 필요한 정보의 형태로 변경
    date_fmt = '%b%d,%Y%I:%M:%S%p'
    df['beginDate']=pd.to_datetime(df['beginDate'],format=date_fmt)
    df['endDate']=pd.to_datetime(df['endDate'],format=date_fmt)
    df['date'] = df['beginDate'].map(lambda x: x.strftime('%Y%m%d'))
    df['dpt'] = df['beginDate'].map(lambda x: x.strftime('%H:%M'))
    df['arr'] = df['endDate'].map(lambda x: x.strftime('%H:%M'))
    heads_map = {
        'flightNumber':'flt',
        'amountWithoutTax':'fare',
        'numberOfSeatsLeft':'seat',
    }
    data_heads = ['date','flt','dpt','arr','fare','tax','seat']
    df.rename(columns=heads_map,inplace=True)
    return df[data_heads]


## 하루치 정보 읽어오기
def read_LJ_1day_fare(dpt,arr,dpt_date):
    ## 정보 읽어오기
    df = raw_to_df(crawling_LJ_data(dpt,arr,dpt_date))
    ## 통계 정보 처리
    if df is not None:
        stat = stat_fare(df,columns=['fare'])
        df.ix[len(df)] = [dpt_date.replace('-',''),'min','max','mean',stat[0],stat[1],stat[2]]
    return df

## 정해진 기간의 데이터 읽어오기, 기본 30일
def read_LJ_date_range_fare(dpt,arr,start=0,end=31):
    # 기본 30일간 데이터 읽어서 파일로 저장
    date_range = [ (datetime.today()+timedelta(1)*i).strftime('%Y%m%d') for i in range(start,end)]
    fare_list = []
    for d in date_range:
        try:
            fare_df = read_LJ_1day_fare(dpt,arr,d)
            if fare_df is not None:
                fare_list.append(fare_df)
        except Exception as e:
            print('****** Error occured : ',e)
    result = pd.concat(fare_list,ignore_index=True)
    print('++++++++++Total : ', len(result))
    ## 파일 저장
    result.to_excel('{}/{}_{}_{}_{}_{}_{}.xls'.format('excel','LJ',dpt[:3],arr[:3],start,end,datetime.today().strftime('%Y%m%d%H%M')))
    return result

In [2]:
dpt = 'ICN/KOR' # 'ICN/KOR'
arr = 'OKA/JPN' # 'NRT/JPN'
dpt_date = '20170730'
raw_data = crawling_LJ_data(dpt,arr,dpt_date)
raw_to_df(raw_data)

NameError: name 'crawling_LJ_data' is not defined

In [173]:
dpt = 'ICN/KOR' # 'ICN/KOR'
arr = 'OKA/JPN' # 'NRT/JPN'
dpt_date = '20170530'
read_LJ_1day_fare(dpt,arr,dpt_date)

D:\python\mynotebook\AirlineFareCrawlingProject\common\parsing_util.py:27: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if '' in fare_arr or '0' in fare_arr:

       date  flt    dpt    arr      fare       tax           seat
0  20170530  245  10:35  12:50   88000.0   29200.0       2.000000
1  20170530  245  10:35  12:50  121000.0   29200.0       9.000000
2  20170530  245  10:35  12:50  297000.0   29200.0       9.000000
3  20170530  min    max   mean   88000.0  297000.0  168666.666667

In [197]:
## 정해진 기간의 데이터 읽어오기
dpt, arr = 'ICN/KOR','NRT/JPN'
start,end =1, 31 ## 읽어올 데이터 기간
read_LJ_date_range_fare(dpt,arr,start,end)

Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170429
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170430

D:\python\mynotebook\AirlineFareCrawlingProject\common\parsing_util.py:27: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if '' in fare_arr or '0' in fare_arr:

End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170501
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170502
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170503
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170504
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170505
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170506
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170507
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170508
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170509
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170510
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170511
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170512
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170513
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170514
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170515
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170516
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170517
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170518
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170519
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170520
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170521
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170522
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170523
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170524
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170525
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170526
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170527
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170528
End crawling
++++++++++Total :  175

         date  flt    dpt    arr      fare       tax           seat
0    20170429  201  07:25  09:50  242000.0   29200.0       1.000000
1    20170429  201  07:25  09:50  270000.0   29200.0       9.000000
2    20170429  203  14:25  16:55  220000.0   29200.0       2.000000
3    20170429  203  14:25  16:55  270000.0   29200.0       2.000000
4    20170429  min    max   mean  220000.0  270000.0  244000.000000
5    20170430  201  07:25  09:50  165000.0   29200.0       4.000000
6    20170430  201  07:25  09:50  270000.0   29200.0       9.000000
7    20170430  203  14:25  16:55  165000.0   29200.0       5.000000
8    20170430  203  14:25  16:55  270000.0   29200.0       9.000000
9    20170430  min    max   mean  165000.0  270000.0  217500.000000
10   20170501  201  07:25  09:50  127000.0   29200.0       4.000000
11   20170501  201  07:25  09:50  270000.0   29200.0       9.000000
12   20170501  203  14:25  16:55  127000.0   29200.0       2.000000
13   20170501  203  14:25  16:55  270000.0   29200.0       9.000000
14   20170501  min    max   mean  127000.0  270000.0  198500.000000
15   20170502  201  07:25  09:50  127000.0   29200.0       3.000000
16   20170502  201  07:25  09:50  270000.0   29200.0       9.000000
17   20170502  203  14:25  16:55  143000.0   29200.0       1.000000
18   20170502  203  14:25  16:55  270000.0   29200.0       9.000000
19   20170502  min    max   mean  127000.0  270000.0  180000.000000
20   20170503  203  14:25  16:55  297000.0   29200.0       9.000000
21   20170503  min    max   mean  297000.0  297000.0  297000.000000
22   20170504  201  07:25  09:50  204000.0   29200.0       6.000000
23   20170504  201  07:25  09:50  270000.0   29200.0       9.000000
24   20170504  203  14:25  16:55  182000.0   29200.0       1.000000
25   20170504  203  14:25  16:55  270000.0   29200.0       9.000000
26   20170504  min    max   mean  182000.0  270000.0  218666.666667
27   20170505  201  07:25  09:50  242000.0   29200.0       1.000000
28   20170505  201  07:25  09:50  270000.0   29200.0       4.000000
29   20170505  203  14:35  16:55  270000.0   29200.0       7.000000
..        ...  ...    ...    ...       ...       ...            ...
145  20170524  203  14:25  16:55  127000.0   29200.0       9.000000
146  20170524  203  14:25  16:55  270000.0   29200.0       9.000000
147  20170524  min    max   mean   72000.0  270000.0  138000.000000
148  20170525  201  07:25  09:50   83000.0   29200.0       9.000000
149  20170525  201  07:25  09:50  127000.0   29200.0       9.000000
150  20170525  201  07:25  09:50  270000.0   29200.0       9.000000
151  20170525  203  14:25  16:55   99000.0   29200.0       4.000000
152  20170525  203  14:25  16:55  127000.0   29200.0       9.000000
153  20170525  203  14:25  16:55  270000.0   29200.0       9.000000
154  20170525  min    max   mean   83000.0  270000.0  144750.000000
155  20170526  201  07:25  09:50   72000.0   29200.0       1.000000
156  20170526  201  07:25  09:50  127000.0   29200.0       9.000000
157  20170526  201  07:25  09:50  270000.0   29200.0       9.000000
158  20170526  203  14:35  16:55   99000.0   29200.0       7.000000
159  20170526  203  14:35  16:55  127000.0   29200.0       9.000000
160  20170526  203  14:35  16:55  270000.0   29200.0       9.000000
161  20170526  min    max   mean   72000.0  270000.0  142000.000000
162  20170527  201  07:25  09:50  143000.0   29200.0       7.000000
163  20170527  201  07:25  09:50  270000.0   29200.0       9.000000
164  20170527  203  14:25  16:55   83000.0   29200.0       5.000000
165  20170527  203  14:25  16:55  127000.0   29200.0       9.000000
166  20170527  203  14:25  16:55  270000.0   29200.0       9.000000
167  20170527  min    max   mean   83000.0  270000.0  155750.000000
168  20170528  201  07:25  09:50   83000.0   29200.0       1.000000
169  20170528  201  07:25  09:50  127000.0   29200.0       9.000000
170  20170528  201  07:25  09:50  270000.0   29200.0       9.000000
171  20170528  203  14:25  16:55   72000.0   29200.0       6.000000
172  20170528  203  14:25  16:55  127000.0   29200.0       9.000000
173  20170528  203  14:25  16:55  270000.0   29200.0       9.000000
174  20170528  min    max   mean   72000.0  270000.0  138000.000000

[175 rows x 7 columns]

In [192]:
## 정해진 기간의 데이터 읽어오기
dpt, arr = 'ICN/KOR','NRT/JPN'
start,end =31, 45 ## 읽어올 데이터 기간
read_LJ_date_range_fare(dpt,arr,start,end)

datetime.datetime(2017, 6, 5, 7, 5)

In [198]:
## 정해진 기간의 데이터 읽어오기
dpt, arr = 'ICN/KOR','NRT/JPN'
start,end =45, 90 ## 읽어올 데이터 기간
read_LJ_date_range_fare(dpt,arr,start,end)

Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170612
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170613

D:\python\mynotebook\AirlineFareCrawlingProject\common\parsing_util.py:27: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if '' in fare_arr or '0' in fare_arr:

End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170614
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170615
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170616
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170617
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170618
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170619
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170620
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170621
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170622
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170623
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170624
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170625
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170626
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170627
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170628
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170629
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170630
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170701
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170702
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170703
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170704
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170705
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170706
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170707
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170708
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170709
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170710
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170711
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170712
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170713
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170714
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170715
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170716
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170717
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170718
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170719
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170720
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170721
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170722
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170723
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170724
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170725
End crawling
Crawling jinair homepage schedule site
Param :  ICN/KOR NRT/JPN 20170726
End crawling
++++++++++Total :  285

         date  flt    dpt    arr      fare       tax           seat
0    20170612  201  07:25  09:50   72000.0   29200.0       6.000000
1    20170612  201  07:25  09:50  127000.0   29200.0       9.000000
2    20170612  201  07:25  09:50  270000.0   29200.0       9.000000
3    20170612  min    max   mean   72000.0  270000.0  156333.333333
4    20170613  201  07:25  09:50   72000.0   29200.0       6.000000
5    20170613  201  07:25  09:50  127000.0   29200.0       9.000000
6    20170613  201  07:25  09:50  270000.0   29200.0       9.000000
7    20170613  203  14:25  16:55   72000.0   29200.0       5.000000
8    20170613  203  14:25  16:55  127000.0   29200.0       9.000000
9    20170613  203  14:25  16:55  270000.0   29200.0       9.000000
10   20170613  min    max   mean   72000.0  270000.0  156333.333333
11   20170614  201  07:25  09:50   72000.0   29200.0       6.000000
12   20170614  201  07:25  09:50  127000.0   29200.0       9.000000
13   20170614  201  07:25  09:50  270000.0   29200.0       9.000000
14   20170614  203  14:25  16:55   72000.0   29200.0       6.000000
15   20170614  203  14:25  16:55  127000.0   29200.0       9.000000
16   20170614  203  14:25  16:55  270000.0   29200.0       9.000000
17   20170614  min    max   mean   72000.0  270000.0  156333.333333
18   20170615  201  07:25  09:50   72000.0   29200.0       5.000000
19   20170615  201  07:25  09:50  127000.0   29200.0       9.000000
20   20170615  201  07:25  09:50  270000.0   29200.0       9.000000
21   20170615  203  14:25  16:55   83000.0   29200.0       4.000000
22   20170615  203  14:25  16:55  127000.0   29200.0       9.000000
23   20170615  203  14:25  16:55  270000.0   29200.0       9.000000
24   20170615  min    max   mean   72000.0  270000.0  138000.000000
25   20170616  201  07:25  09:50   72000.0   29200.0       2.000000
26   20170616  201  07:25  09:50  127000.0   29200.0       9.000000
27   20170616  201  07:25  09:50  270000.0   29200.0       9.000000
28   20170616  203  14:35  16:55   83000.0   29200.0       6.000000
29   20170616  203  14:35  16:55  127000.0   29200.0       9.000000
..        ...  ...    ...    ...       ...       ...            ...
255  20170721  201  07:25  09:50  127000.0   29200.0       1.000000
256  20170721  201  07:25  09:50  270000.0   29200.0       9.000000
257  20170721  203  14:25  16:55  127000.0   29200.0       5.000000
258  20170721  203  14:25  16:55  270000.0   29200.0       9.000000
259  20170721  min    max   mean  127000.0  270000.0  198500.000000
260  20170722  201  07:25  09:50  127000.0   29200.0       3.000000
261  20170722  201  07:25  09:50  270000.0   29200.0       9.000000
262  20170722  203  14:25  16:55  127000.0   29200.0       1.000000
263  20170722  203  14:25  16:55  270000.0   29200.0       9.000000
264  20170722  min    max   mean  127000.0  270000.0  198500.000000
265  20170723  201  07:25  09:50  127000.0   29200.0       2.000000
266  20170723  201  07:25  09:50  270000.0   29200.0       9.000000
267  20170723  203  14:25  16:55  127000.0   29200.0       2.000000
268  20170723  203  14:25  16:55  270000.0   29200.0       9.000000
269  20170723  min    max   mean  127000.0  270000.0  198500.000000
270  20170724  201  07:25  09:50  143000.0   29200.0       2.000000
271  20170724  201  07:25  09:50  270000.0   29200.0       9.000000
272  20170724  203  14:25  16:55  127000.0   29200.0       1.000000
273  20170724  203  14:25  16:55  270000.0   29200.0       9.000000
274  20170724  min    max   mean  127000.0  270000.0  180000.000000
275  20170725  201  07:25  09:50  143000.0   29200.0       4.000000
276  20170725  201  07:25  09:50  270000.0   29200.0       9.000000
277  20170725  203  14:25  16:55  127000.0   29200.0       6.000000
278  20170725  203  14:25  16:55  270000.0   29200.0       9.000000
279  20170725  min    max   mean  127000.0  270000.0  180000.000000
280  20170726  201  07:25  09:50  143000.0   29200.0       1.000000
281  20170726  201  07:25  09:50  270000.0   29200.0       9.000000
282  20170726  203  14:25  16:55  143000.0   29200.0       1.000000
283  20170726  203  14:25  16:55  270000.0   29200.0       9.000000
284  20170726  min    max   mean  143000.0  270000.0  206500.000000

[285 rows x 7 columns]